/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package fr.sciencespo.medialab.hci.memorystructure.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class NodeLink implements org.apache.thrift.TBase<NodeLink, NodeLink._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("NodeLink");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField SOURCE_LRU_FIELD_DESC = new org.apache.thrift.protocol.TField("sourceLRU", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField TARGET_LRU_FIELD_DESC = new org.apache.thrift.protocol.TField("targetLRU", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField WEIGHT_FIELD_DESC = new org.apache.thrift.protocol.TField("weight", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField CREATION_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("creationDate", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField LAST_MODIFICATION_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("lastModificationDate", org.apache.thrift.protocol.TType.STRING, (short)6);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new NodeLinkStandardSchemeFactory());
    schemes.put(TupleScheme.class, new NodeLinkTupleSchemeFactory());
  }

  public String id; // required
  public String sourceLRU; // required
  public String targetLRU; // required
  public int weight; // required
  public String creationDate; // required
  public String lastModificationDate; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    SOURCE_LRU((short)2, "sourceLRU"),
    TARGET_LRU((short)3, "targetLRU"),
    WEIGHT((short)4, "weight"),
    CREATION_DATE((short)5, "creationDate"),
    LAST_MODIFICATION_DATE((short)6, "lastModificationDate");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // SOURCE_LRU
          return SOURCE_LRU;
        case 3: // TARGET_LRU
          return TARGET_LRU;
        case 4: // WEIGHT
          return WEIGHT;
        case 5: // CREATION_DATE
          return CREATION_DATE;
        case 6: // LAST_MODIFICATION_DATE
          return LAST_MODIFICATION_DATE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __WEIGHT_ISSET_ID = 0;
  private BitSet __isset_bit_vector = new BitSet(1);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SOURCE_LRU, new org.apache.thrift.meta_data.FieldMetaData("sourceLRU", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TARGET_LRU, new org.apache.thrift.meta_data.FieldMetaData("targetLRU", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.WEIGHT, new org.apache.thrift.meta_data.FieldMetaData("weight", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CREATION_DATE, new org.apache.thrift.meta_data.FieldMetaData("creationDate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LAST_MODIFICATION_DATE, new org.apache.thrift.meta_data.FieldMetaData("lastModificationDate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(NodeLink.class, metaDataMap);
  }

  public NodeLink() {
    this.weight = 1;

  }

  public NodeLink(
    String id,
    String sourceLRU,
    String targetLRU,
    int weight,
    String creationDate,
    String lastModificationDate)
  {
    this();
    this.id = id;
    this.sourceLRU = sourceLRU;
    this.targetLRU = targetLRU;
    this.weight = weight;
    setWeightIsSet(true);
    this.creationDate = creationDate;
    this.lastModificationDate = lastModificationDate;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public NodeLink(NodeLink other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    if (other.isSetId()) {
      this.id = other.id;
    }
    if (other.isSetSourceLRU()) {
      this.sourceLRU = other.sourceLRU;
    }
    if (other.isSetTargetLRU()) {
      this.targetLRU = other.targetLRU;
    }
    this.weight = other.weight;
    if (other.isSetCreationDate()) {
      this.creationDate = other.creationDate;
    }
    if (other.isSetLastModificationDate()) {
      this.lastModificationDate = other.lastModificationDate;
    }
  }

  public NodeLink deepCopy() {
    return new NodeLink(this);
  }

  @Override
  public void clear() {
    this.id = null;
    this.sourceLRU = null;
    this.targetLRU = null;
    this.weight = 1;

    this.creationDate = null;
    this.lastModificationDate = null;
  }

  public String getId() {
    return this.id;
  }

  public NodeLink setId(String id) {
    this.id = id;
    return this;
  }

  public void unsetId() {
    this.id = null;
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return this.id != null;
  }

  public void setIdIsSet(boolean value) {
    if (!value) {
      this.id = null;
    }
  }

  public String getSourceLRU() {
    return this.sourceLRU;
  }

  public NodeLink setSourceLRU(String sourceLRU) {
    this.sourceLRU = sourceLRU;
    return this;
  }

  public void unsetSourceLRU() {
    this.sourceLRU = null;
  }

  /** Returns true if field sourceLRU is set (has been assigned a value) and false otherwise */
  public boolean isSetSourceLRU() {
    return this.sourceLRU != null;
  }

  public void setSourceLRUIsSet(boolean value) {
    if (!value) {
      this.sourceLRU = null;
    }
  }

  public String getTargetLRU() {
    return this.targetLRU;
  }

  public NodeLink setTargetLRU(String targetLRU) {
    this.targetLRU = targetLRU;
    return this;
  }

  public void unsetTargetLRU() {
    this.targetLRU = null;
  }

  /** Returns true if field targetLRU is set (has been assigned a value) and false otherwise */
  public boolean isSetTargetLRU() {
    return this.targetLRU != null;
  }

  public void setTargetLRUIsSet(boolean value) {
    if (!value) {
      this.targetLRU = null;
    }
  }

  public int getWeight() {
    return this.weight;
  }

  public NodeLink setWeight(int weight) {
    this.weight = weight;
    setWeightIsSet(true);
    return this;
  }

  public void unsetWeight() {
    __isset_bit_vector.clear(__WEIGHT_ISSET_ID);
  }

  /** Returns true if field weight is set (has been assigned a value) and false otherwise */
  public boolean isSetWeight() {
    return __isset_bit_vector.get(__WEIGHT_ISSET_ID);
  }

  public void setWeightIsSet(boolean value) {
    __isset_bit_vector.set(__WEIGHT_ISSET_ID, value);
  }

  public String getCreationDate() {
    return this.creationDate;
  }

  public NodeLink setCreationDate(String creationDate) {
    this.creationDate = creationDate;
    return this;
  }

  public void unsetCreationDate() {
    this.creationDate = null;
  }

  /** Returns true if field creationDate is set (has been assigned a value) and false otherwise */
  public boolean isSetCreationDate() {
    return this.creationDate != null;
  }

  public void setCreationDateIsSet(boolean value) {
    if (!value) {
      this.creationDate = null;
    }
  }

  public String getLastModificationDate() {
    return this.lastModificationDate;
  }

  public NodeLink setLastModificationDate(String lastModificationDate) {
    this.lastModificationDate = lastModificationDate;
    return this;
  }

  public void unsetLastModificationDate() {
    this.lastModificationDate = null;
  }

  /** Returns true if field lastModificationDate is set (has been assigned a value) and false otherwise */
  public boolean isSetLastModificationDate() {
    return this.lastModificationDate != null;
  }

  public void setLastModificationDateIsSet(boolean value) {
    if (!value) {
      this.lastModificationDate = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((String)value);
      }
      break;

    case SOURCE_LRU:
      if (value == null) {
        unsetSourceLRU();
      } else {
        setSourceLRU((String)value);
      }
      break;

    case TARGET_LRU:
      if (value == null) {
        unsetTargetLRU();
      } else {
        setTargetLRU((String)value);
      }
      break;

    case WEIGHT:
      if (value == null) {
        unsetWeight();
      } else {
        setWeight((Integer)value);
      }
      break;

    case CREATION_DATE:
      if (value == null) {
        unsetCreationDate();
      } else {
        setCreationDate((String)value);
      }
      break;

    case LAST_MODIFICATION_DATE:
      if (value == null) {
        unsetLastModificationDate();
      } else {
        setLastModificationDate((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case SOURCE_LRU:
      return getSourceLRU();

    case TARGET_LRU:
      return getTargetLRU();

    case WEIGHT:
      return Integer.valueOf(getWeight());

    case CREATION_DATE:
      return getCreationDate();

    case LAST_MODIFICATION_DATE:
      return getLastModificationDate();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case SOURCE_LRU:
      return isSetSourceLRU();
    case TARGET_LRU:
      return isSetTargetLRU();
    case WEIGHT:
      return isSetWeight();
    case CREATION_DATE:
      return isSetCreationDate();
    case LAST_MODIFICATION_DATE:
      return isSetLastModificationDate();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof NodeLink)
      return this.equals((NodeLink)that);
    return false;
  }

  public boolean equals(NodeLink that) {
    if (that == null)
      return false;

    boolean this_present_id = true && this.isSetId();
    boolean that_present_id = true && that.isSetId();
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (!this.id.equals(that.id))
        return false;
    }

    boolean this_present_sourceLRU = true && this.isSetSourceLRU();
    boolean that_present_sourceLRU = true && that.isSetSourceLRU();
    if (this_present_sourceLRU || that_present_sourceLRU) {
      if (!(this_present_sourceLRU && that_present_sourceLRU))
        return false;
      if (!this.sourceLRU.equals(that.sourceLRU))
        return false;
    }

    boolean this_present_targetLRU = true && this.isSetTargetLRU();
    boolean that_present_targetLRU = true && that.isSetTargetLRU();
    if (this_present_targetLRU || that_present_targetLRU) {
      if (!(this_present_targetLRU && that_present_targetLRU))
        return false;
      if (!this.targetLRU.equals(that.targetLRU))
        return false;
    }

    boolean this_present_weight = true;
    boolean that_present_weight = true;
    if (this_present_weight || that_present_weight) {
      if (!(this_present_weight && that_present_weight))
        return false;
      if (this.weight != that.weight)
        return false;
    }

    boolean this_present_creationDate = true && this.isSetCreationDate();
    boolean that_present_creationDate = true && that.isSetCreationDate();
    if (this_present_creationDate || that_present_creationDate) {
      if (!(this_present_creationDate && that_present_creationDate))
        return false;
      if (!this.creationDate.equals(that.creationDate))
        return false;
    }

    boolean this_present_lastModificationDate = true && this.isSetLastModificationDate();
    boolean that_present_lastModificationDate = true && that.isSetLastModificationDate();
    if (this_present_lastModificationDate || that_present_lastModificationDate) {
      if (!(this_present_lastModificationDate && that_present_lastModificationDate))
        return false;
      if (!this.lastModificationDate.equals(that.lastModificationDate))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(NodeLink other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    NodeLink typedOther = (NodeLink)other;

    lastComparison = Boolean.valueOf(isSetId()).compareTo(typedOther.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, typedOther.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSourceLRU()).compareTo(typedOther.isSetSourceLRU());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSourceLRU()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sourceLRU, typedOther.sourceLRU);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTargetLRU()).compareTo(typedOther.isSetTargetLRU());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTargetLRU()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.targetLRU, typedOther.targetLRU);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetWeight()).compareTo(typedOther.isSetWeight());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWeight()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.weight, typedOther.weight);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCreationDate()).compareTo(typedOther.isSetCreationDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreationDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.creationDate, typedOther.creationDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastModificationDate()).compareTo(typedOther.isSetLastModificationDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastModificationDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastModificationDate, typedOther.lastModificationDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("NodeLink(");
    boolean first = true;

    sb.append("id:");
    if (this.id == null) {
      sb.append("null");
    } else {
      sb.append(this.id);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("sourceLRU:");
    if (this.sourceLRU == null) {
      sb.append("null");
    } else {
      sb.append(this.sourceLRU);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("targetLRU:");
    if (this.targetLRU == null) {
      sb.append("null");
    } else {
      sb.append(this.targetLRU);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("weight:");
    sb.append(this.weight);
    first = false;
    if (!first) sb.append(", ");
    sb.append("creationDate:");
    if (this.creationDate == null) {
      sb.append("null");
    } else {
      sb.append(this.creationDate);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastModificationDate:");
    if (this.lastModificationDate == null) {
      sb.append("null");
    } else {
      sb.append(this.lastModificationDate);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class NodeLinkStandardSchemeFactory implements SchemeFactory {
    public NodeLinkStandardScheme getScheme() {
      return new NodeLinkStandardScheme();
    }
  }

  private static class NodeLinkStandardScheme extends StandardScheme<NodeLink> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, NodeLink struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.id = iprot.readString();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SOURCE_LRU
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.sourceLRU = iprot.readString();
              struct.setSourceLRUIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TARGET_LRU
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.targetLRU = iprot.readString();
              struct.setTargetLRUIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // WEIGHT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.weight = iprot.readI32();
              struct.setWeightIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // CREATION_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.creationDate = iprot.readString();
              struct.setCreationDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // LAST_MODIFICATION_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.lastModificationDate = iprot.readString();
              struct.setLastModificationDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, NodeLink struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.id != null) {
        oprot.writeFieldBegin(ID_FIELD_DESC);
        oprot.writeString(struct.id);
        oprot.writeFieldEnd();
      }
      if (struct.sourceLRU != null) {
        oprot.writeFieldBegin(SOURCE_LRU_FIELD_DESC);
        oprot.writeString(struct.sourceLRU);
        oprot.writeFieldEnd();
      }
      if (struct.targetLRU != null) {
        oprot.writeFieldBegin(TARGET_LRU_FIELD_DESC);
        oprot.writeString(struct.targetLRU);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(WEIGHT_FIELD_DESC);
      oprot.writeI32(struct.weight);
      oprot.writeFieldEnd();
      if (struct.creationDate != null) {
        oprot.writeFieldBegin(CREATION_DATE_FIELD_DESC);
        oprot.writeString(struct.creationDate);
        oprot.writeFieldEnd();
      }
      if (struct.lastModificationDate != null) {
        oprot.writeFieldBegin(LAST_MODIFICATION_DATE_FIELD_DESC);
        oprot.writeString(struct.lastModificationDate);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class NodeLinkTupleSchemeFactory implements SchemeFactory {
    public NodeLinkTupleScheme getScheme() {
      return new NodeLinkTupleScheme();
    }
  }

  private static class NodeLinkTupleScheme extends TupleScheme<NodeLink> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, NodeLink struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetSourceLRU()) {
        optionals.set(1);
      }
      if (struct.isSetTargetLRU()) {
        optionals.set(2);
      }
      if (struct.isSetWeight()) {
        optionals.set(3);
      }
      if (struct.isSetCreationDate()) {
        optionals.set(4);
      }
      if (struct.isSetLastModificationDate()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetId()) {
        oprot.writeString(struct.id);
      }
      if (struct.isSetSourceLRU()) {
        oprot.writeString(struct.sourceLRU);
      }
      if (struct.isSetTargetLRU()) {
        oprot.writeString(struct.targetLRU);
      }
      if (struct.isSetWeight()) {
        oprot.writeI32(struct.weight);
      }
      if (struct.isSetCreationDate()) {
        oprot.writeString(struct.creationDate);
      }
      if (struct.isSetLastModificationDate()) {
        oprot.writeString(struct.lastModificationDate);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, NodeLink struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.id = iprot.readString();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.sourceLRU = iprot.readString();
        struct.setSourceLRUIsSet(true);
      }
      if (incoming.get(2)) {
        struct.targetLRU = iprot.readString();
        struct.setTargetLRUIsSet(true);
      }
      if (incoming.get(3)) {
        struct.weight = iprot.readI32();
        struct.setWeightIsSet(true);
      }
      if (incoming.get(4)) {
        struct.creationDate = iprot.readString();
        struct.setCreationDateIsSet(true);
      }
      if (incoming.get(5)) {
        struct.lastModificationDate = iprot.readString();
        struct.setLastModificationDateIsSet(true);
      }
    }
  }

}

