/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package fr.sciencespo.medialab.hci.memorystructure.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class PageItem implements org.apache.thrift.TBase<PageItem, PageItem._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PageItem");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField URL_FIELD_DESC = new org.apache.thrift.protocol.TField("url", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField LRU_FIELD_DESC = new org.apache.thrift.protocol.TField("lru", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField CRAWLER_TIMESTAMP_FIELD_DESC = new org.apache.thrift.protocol.TField("crawlerTimestamp", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField HTTP_STATUS_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("httpStatusCode", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField DEPTH_FIELD_DESC = new org.apache.thrift.protocol.TField("depth", org.apache.thrift.protocol.TType.I32, (short)6);
  private static final org.apache.thrift.protocol.TField ERROR_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("errorCode", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField IS_FULL_PRECISION_FIELD_DESC = new org.apache.thrift.protocol.TField("isFullPrecision", org.apache.thrift.protocol.TType.BOOL, (short)8);
  private static final org.apache.thrift.protocol.TField IS_NODE_FIELD_DESC = new org.apache.thrift.protocol.TField("isNode", org.apache.thrift.protocol.TType.BOOL, (short)9);
  private static final org.apache.thrift.protocol.TField METADATA_ITEMS_FIELD_DESC = new org.apache.thrift.protocol.TField("metadataItems", org.apache.thrift.protocol.TType.MAP, (short)10);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PageItemStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PageItemTupleSchemeFactory());
  }

  public String id; // required
  public String url; // required
  public String lru; // required
  public String crawlerTimestamp; // required
  public int httpStatusCode; // required
  public int depth; // required
  public String errorCode; // required
  public boolean isFullPrecision; // required
  public boolean isNode; // required
  public Map<String,Set<String>> metadataItems; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    URL((short)2, "url"),
    LRU((short)3, "lru"),
    CRAWLER_TIMESTAMP((short)4, "crawlerTimestamp"),
    HTTP_STATUS_CODE((short)5, "httpStatusCode"),
    DEPTH((short)6, "depth"),
    ERROR_CODE((short)7, "errorCode"),
    IS_FULL_PRECISION((short)8, "isFullPrecision"),
    IS_NODE((short)9, "isNode"),
    METADATA_ITEMS((short)10, "metadataItems");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // URL
          return URL;
        case 3: // LRU
          return LRU;
        case 4: // CRAWLER_TIMESTAMP
          return CRAWLER_TIMESTAMP;
        case 5: // HTTP_STATUS_CODE
          return HTTP_STATUS_CODE;
        case 6: // DEPTH
          return DEPTH;
        case 7: // ERROR_CODE
          return ERROR_CODE;
        case 8: // IS_FULL_PRECISION
          return IS_FULL_PRECISION;
        case 9: // IS_NODE
          return IS_NODE;
        case 10: // METADATA_ITEMS
          return METADATA_ITEMS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __HTTPSTATUSCODE_ISSET_ID = 0;
  private static final int __DEPTH_ISSET_ID = 1;
  private static final int __ISFULLPRECISION_ISSET_ID = 2;
  private static final int __ISNODE_ISSET_ID = 3;
  private BitSet __isset_bit_vector = new BitSet(4);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.URL, new org.apache.thrift.meta_data.FieldMetaData("url", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LRU, new org.apache.thrift.meta_data.FieldMetaData("lru", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CRAWLER_TIMESTAMP, new org.apache.thrift.meta_data.FieldMetaData("crawlerTimestamp", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.HTTP_STATUS_CODE, new org.apache.thrift.meta_data.FieldMetaData("httpStatusCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DEPTH, new org.apache.thrift.meta_data.FieldMetaData("depth", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ERROR_CODE, new org.apache.thrift.meta_data.FieldMetaData("errorCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IS_FULL_PRECISION, new org.apache.thrift.meta_data.FieldMetaData("isFullPrecision", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.IS_NODE, new org.apache.thrift.meta_data.FieldMetaData("isNode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.METADATA_ITEMS, new org.apache.thrift.meta_data.FieldMetaData("metadataItems", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PageItem.class, metaDataMap);
  }

  public PageItem() {
    this.isFullPrecision = false;

  }

  public PageItem(
    String id,
    String url,
    String lru,
    String crawlerTimestamp,
    int httpStatusCode,
    int depth,
    String errorCode,
    boolean isFullPrecision,
    boolean isNode,
    Map<String,Set<String>> metadataItems)
  {
    this();
    this.id = id;
    this.url = url;
    this.lru = lru;
    this.crawlerTimestamp = crawlerTimestamp;
    this.httpStatusCode = httpStatusCode;
    setHttpStatusCodeIsSet(true);
    this.depth = depth;
    setDepthIsSet(true);
    this.errorCode = errorCode;
    this.isFullPrecision = isFullPrecision;
    setIsFullPrecisionIsSet(true);
    this.isNode = isNode;
    setIsNodeIsSet(true);
    this.metadataItems = metadataItems;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PageItem(PageItem other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    if (other.isSetId()) {
      this.id = other.id;
    }
    if (other.isSetUrl()) {
      this.url = other.url;
    }
    if (other.isSetLru()) {
      this.lru = other.lru;
    }
    if (other.isSetCrawlerTimestamp()) {
      this.crawlerTimestamp = other.crawlerTimestamp;
    }
    this.httpStatusCode = other.httpStatusCode;
    this.depth = other.depth;
    if (other.isSetErrorCode()) {
      this.errorCode = other.errorCode;
    }
    this.isFullPrecision = other.isFullPrecision;
    this.isNode = other.isNode;
    if (other.isSetMetadataItems()) {
      Map<String,Set<String>> __this__metadataItems = new HashMap<String,Set<String>>();
      for (Map.Entry<String, Set<String>> other_element : other.metadataItems.entrySet()) {

        String other_element_key = other_element.getKey();
        Set<String> other_element_value = other_element.getValue();

        String __this__metadataItems_copy_key = other_element_key;

        Set<String> __this__metadataItems_copy_value = new HashSet<String>();
        for (String other_element_value_element : other_element_value) {
          __this__metadataItems_copy_value.add(other_element_value_element);
        }

        __this__metadataItems.put(__this__metadataItems_copy_key, __this__metadataItems_copy_value);
      }
      this.metadataItems = __this__metadataItems;
    }
  }

  public PageItem deepCopy() {
    return new PageItem(this);
  }

  @Override
  public void clear() {
    this.id = null;
    this.url = null;
    this.lru = null;
    this.crawlerTimestamp = null;
    setHttpStatusCodeIsSet(false);
    this.httpStatusCode = 0;
    setDepthIsSet(false);
    this.depth = 0;
    this.errorCode = null;
    this.isFullPrecision = false;

    setIsNodeIsSet(false);
    this.isNode = false;
    this.metadataItems = null;
  }

  public String getId() {
    return this.id;
  }

  public PageItem setId(String id) {
    this.id = id;
    return this;
  }

  public void unsetId() {
    this.id = null;
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return this.id != null;
  }

  public void setIdIsSet(boolean value) {
    if (!value) {
      this.id = null;
    }
  }

  public String getUrl() {
    return this.url;
  }

  public PageItem setUrl(String url) {
    this.url = url;
    return this;
  }

  public void unsetUrl() {
    this.url = null;
  }

  /** Returns true if field url is set (has been assigned a value) and false otherwise */
  public boolean isSetUrl() {
    return this.url != null;
  }

  public void setUrlIsSet(boolean value) {
    if (!value) {
      this.url = null;
    }
  }

  public String getLru() {
    return this.lru;
  }

  public PageItem setLru(String lru) {
    this.lru = lru;
    return this;
  }

  public void unsetLru() {
    this.lru = null;
  }

  /** Returns true if field lru is set (has been assigned a value) and false otherwise */
  public boolean isSetLru() {
    return this.lru != null;
  }

  public void setLruIsSet(boolean value) {
    if (!value) {
      this.lru = null;
    }
  }

  public String getCrawlerTimestamp() {
    return this.crawlerTimestamp;
  }

  public PageItem setCrawlerTimestamp(String crawlerTimestamp) {
    this.crawlerTimestamp = crawlerTimestamp;
    return this;
  }

  public void unsetCrawlerTimestamp() {
    this.crawlerTimestamp = null;
  }

  /** Returns true if field crawlerTimestamp is set (has been assigned a value) and false otherwise */
  public boolean isSetCrawlerTimestamp() {
    return this.crawlerTimestamp != null;
  }

  public void setCrawlerTimestampIsSet(boolean value) {
    if (!value) {
      this.crawlerTimestamp = null;
    }
  }

  public int getHttpStatusCode() {
    return this.httpStatusCode;
  }

  public PageItem setHttpStatusCode(int httpStatusCode) {
    this.httpStatusCode = httpStatusCode;
    setHttpStatusCodeIsSet(true);
    return this;
  }

  public void unsetHttpStatusCode() {
    __isset_bit_vector.clear(__HTTPSTATUSCODE_ISSET_ID);
  }

  /** Returns true if field httpStatusCode is set (has been assigned a value) and false otherwise */
  public boolean isSetHttpStatusCode() {
    return __isset_bit_vector.get(__HTTPSTATUSCODE_ISSET_ID);
  }

  public void setHttpStatusCodeIsSet(boolean value) {
    __isset_bit_vector.set(__HTTPSTATUSCODE_ISSET_ID, value);
  }

  public int getDepth() {
    return this.depth;
  }

  public PageItem setDepth(int depth) {
    this.depth = depth;
    setDepthIsSet(true);
    return this;
  }

  public void unsetDepth() {
    __isset_bit_vector.clear(__DEPTH_ISSET_ID);
  }

  /** Returns true if field depth is set (has been assigned a value) and false otherwise */
  public boolean isSetDepth() {
    return __isset_bit_vector.get(__DEPTH_ISSET_ID);
  }

  public void setDepthIsSet(boolean value) {
    __isset_bit_vector.set(__DEPTH_ISSET_ID, value);
  }

  public String getErrorCode() {
    return this.errorCode;
  }

  public PageItem setErrorCode(String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

  public void unsetErrorCode() {
    this.errorCode = null;
  }

  /** Returns true if field errorCode is set (has been assigned a value) and false otherwise */
  public boolean isSetErrorCode() {
    return this.errorCode != null;
  }

  public void setErrorCodeIsSet(boolean value) {
    if (!value) {
      this.errorCode = null;
    }
  }

  public boolean isIsFullPrecision() {
    return this.isFullPrecision;
  }

  public PageItem setIsFullPrecision(boolean isFullPrecision) {
    this.isFullPrecision = isFullPrecision;
    setIsFullPrecisionIsSet(true);
    return this;
  }

  public void unsetIsFullPrecision() {
    __isset_bit_vector.clear(__ISFULLPRECISION_ISSET_ID);
  }

  /** Returns true if field isFullPrecision is set (has been assigned a value) and false otherwise */
  public boolean isSetIsFullPrecision() {
    return __isset_bit_vector.get(__ISFULLPRECISION_ISSET_ID);
  }

  public void setIsFullPrecisionIsSet(boolean value) {
    __isset_bit_vector.set(__ISFULLPRECISION_ISSET_ID, value);
  }

  public boolean isIsNode() {
    return this.isNode;
  }

  public PageItem setIsNode(boolean isNode) {
    this.isNode = isNode;
    setIsNodeIsSet(true);
    return this;
  }

  public void unsetIsNode() {
    __isset_bit_vector.clear(__ISNODE_ISSET_ID);
  }

  /** Returns true if field isNode is set (has been assigned a value) and false otherwise */
  public boolean isSetIsNode() {
    return __isset_bit_vector.get(__ISNODE_ISSET_ID);
  }

  public void setIsNodeIsSet(boolean value) {
    __isset_bit_vector.set(__ISNODE_ISSET_ID, value);
  }

  public int getMetadataItemsSize() {
    return (this.metadataItems == null) ? 0 : this.metadataItems.size();
  }

  public void putToMetadataItems(String key, Set<String> val) {
    if (this.metadataItems == null) {
      this.metadataItems = new HashMap<String,Set<String>>();
    }
    this.metadataItems.put(key, val);
  }

  public Map<String,Set<String>> getMetadataItems() {
    return this.metadataItems;
  }

  public PageItem setMetadataItems(Map<String,Set<String>> metadataItems) {
    this.metadataItems = metadataItems;
    return this;
  }

  public void unsetMetadataItems() {
    this.metadataItems = null;
  }

  /** Returns true if field metadataItems is set (has been assigned a value) and false otherwise */
  public boolean isSetMetadataItems() {
    return this.metadataItems != null;
  }

  public void setMetadataItemsIsSet(boolean value) {
    if (!value) {
      this.metadataItems = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((String)value);
      }
      break;

    case URL:
      if (value == null) {
        unsetUrl();
      } else {
        setUrl((String)value);
      }
      break;

    case LRU:
      if (value == null) {
        unsetLru();
      } else {
        setLru((String)value);
      }
      break;

    case CRAWLER_TIMESTAMP:
      if (value == null) {
        unsetCrawlerTimestamp();
      } else {
        setCrawlerTimestamp((String)value);
      }
      break;

    case HTTP_STATUS_CODE:
      if (value == null) {
        unsetHttpStatusCode();
      } else {
        setHttpStatusCode((Integer)value);
      }
      break;

    case DEPTH:
      if (value == null) {
        unsetDepth();
      } else {
        setDepth((Integer)value);
      }
      break;

    case ERROR_CODE:
      if (value == null) {
        unsetErrorCode();
      } else {
        setErrorCode((String)value);
      }
      break;

    case IS_FULL_PRECISION:
      if (value == null) {
        unsetIsFullPrecision();
      } else {
        setIsFullPrecision((Boolean)value);
      }
      break;

    case IS_NODE:
      if (value == null) {
        unsetIsNode();
      } else {
        setIsNode((Boolean)value);
      }
      break;

    case METADATA_ITEMS:
      if (value == null) {
        unsetMetadataItems();
      } else {
        setMetadataItems((Map<String,Set<String>>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case URL:
      return getUrl();

    case LRU:
      return getLru();

    case CRAWLER_TIMESTAMP:
      return getCrawlerTimestamp();

    case HTTP_STATUS_CODE:
      return Integer.valueOf(getHttpStatusCode());

    case DEPTH:
      return Integer.valueOf(getDepth());

    case ERROR_CODE:
      return getErrorCode();

    case IS_FULL_PRECISION:
      return Boolean.valueOf(isIsFullPrecision());

    case IS_NODE:
      return Boolean.valueOf(isIsNode());

    case METADATA_ITEMS:
      return getMetadataItems();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case URL:
      return isSetUrl();
    case LRU:
      return isSetLru();
    case CRAWLER_TIMESTAMP:
      return isSetCrawlerTimestamp();
    case HTTP_STATUS_CODE:
      return isSetHttpStatusCode();
    case DEPTH:
      return isSetDepth();
    case ERROR_CODE:
      return isSetErrorCode();
    case IS_FULL_PRECISION:
      return isSetIsFullPrecision();
    case IS_NODE:
      return isSetIsNode();
    case METADATA_ITEMS:
      return isSetMetadataItems();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PageItem)
      return this.equals((PageItem)that);
    return false;
  }

  public boolean equals(PageItem that) {
    if (that == null)
      return false;

    boolean this_present_id = true && this.isSetId();
    boolean that_present_id = true && that.isSetId();
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (!this.id.equals(that.id))
        return false;
    }

    boolean this_present_url = true && this.isSetUrl();
    boolean that_present_url = true && that.isSetUrl();
    if (this_present_url || that_present_url) {
      if (!(this_present_url && that_present_url))
        return false;
      if (!this.url.equals(that.url))
        return false;
    }

    boolean this_present_lru = true && this.isSetLru();
    boolean that_present_lru = true && that.isSetLru();
    if (this_present_lru || that_present_lru) {
      if (!(this_present_lru && that_present_lru))
        return false;
      if (!this.lru.equals(that.lru))
        return false;
    }

    boolean this_present_crawlerTimestamp = true && this.isSetCrawlerTimestamp();
    boolean that_present_crawlerTimestamp = true && that.isSetCrawlerTimestamp();
    if (this_present_crawlerTimestamp || that_present_crawlerTimestamp) {
      if (!(this_present_crawlerTimestamp && that_present_crawlerTimestamp))
        return false;
      if (!this.crawlerTimestamp.equals(that.crawlerTimestamp))
        return false;
    }

    boolean this_present_httpStatusCode = true;
    boolean that_present_httpStatusCode = true;
    if (this_present_httpStatusCode || that_present_httpStatusCode) {
      if (!(this_present_httpStatusCode && that_present_httpStatusCode))
        return false;
      if (this.httpStatusCode != that.httpStatusCode)
        return false;
    }

    boolean this_present_depth = true;
    boolean that_present_depth = true;
    if (this_present_depth || that_present_depth) {
      if (!(this_present_depth && that_present_depth))
        return false;
      if (this.depth != that.depth)
        return false;
    }

    boolean this_present_errorCode = true && this.isSetErrorCode();
    boolean that_present_errorCode = true && that.isSetErrorCode();
    if (this_present_errorCode || that_present_errorCode) {
      if (!(this_present_errorCode && that_present_errorCode))
        return false;
      if (!this.errorCode.equals(that.errorCode))
        return false;
    }

    boolean this_present_isFullPrecision = true;
    boolean that_present_isFullPrecision = true;
    if (this_present_isFullPrecision || that_present_isFullPrecision) {
      if (!(this_present_isFullPrecision && that_present_isFullPrecision))
        return false;
      if (this.isFullPrecision != that.isFullPrecision)
        return false;
    }

    boolean this_present_isNode = true;
    boolean that_present_isNode = true;
    if (this_present_isNode || that_present_isNode) {
      if (!(this_present_isNode && that_present_isNode))
        return false;
      if (this.isNode != that.isNode)
        return false;
    }

    boolean this_present_metadataItems = true && this.isSetMetadataItems();
    boolean that_present_metadataItems = true && that.isSetMetadataItems();
    if (this_present_metadataItems || that_present_metadataItems) {
      if (!(this_present_metadataItems && that_present_metadataItems))
        return false;
      if (!this.metadataItems.equals(that.metadataItems))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(PageItem other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    PageItem typedOther = (PageItem)other;

    lastComparison = Boolean.valueOf(isSetId()).compareTo(typedOther.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, typedOther.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUrl()).compareTo(typedOther.isSetUrl());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUrl()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.url, typedOther.url);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLru()).compareTo(typedOther.isSetLru());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLru()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lru, typedOther.lru);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCrawlerTimestamp()).compareTo(typedOther.isSetCrawlerTimestamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCrawlerTimestamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.crawlerTimestamp, typedOther.crawlerTimestamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHttpStatusCode()).compareTo(typedOther.isSetHttpStatusCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHttpStatusCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.httpStatusCode, typedOther.httpStatusCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDepth()).compareTo(typedOther.isSetDepth());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDepth()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.depth, typedOther.depth);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetErrorCode()).compareTo(typedOther.isSetErrorCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetErrorCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.errorCode, typedOther.errorCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIsFullPrecision()).compareTo(typedOther.isSetIsFullPrecision());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsFullPrecision()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isFullPrecision, typedOther.isFullPrecision);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIsNode()).compareTo(typedOther.isSetIsNode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsNode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isNode, typedOther.isNode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMetadataItems()).compareTo(typedOther.isSetMetadataItems());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMetadataItems()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.metadataItems, typedOther.metadataItems);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PageItem(");
    boolean first = true;

    sb.append("id:");
    if (this.id == null) {
      sb.append("null");
    } else {
      sb.append(this.id);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("url:");
    if (this.url == null) {
      sb.append("null");
    } else {
      sb.append(this.url);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("lru:");
    if (this.lru == null) {
      sb.append("null");
    } else {
      sb.append(this.lru);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("crawlerTimestamp:");
    if (this.crawlerTimestamp == null) {
      sb.append("null");
    } else {
      sb.append(this.crawlerTimestamp);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("httpStatusCode:");
    sb.append(this.httpStatusCode);
    first = false;
    if (!first) sb.append(", ");
    sb.append("depth:");
    sb.append(this.depth);
    first = false;
    if (!first) sb.append(", ");
    sb.append("errorCode:");
    if (this.errorCode == null) {
      sb.append("null");
    } else {
      sb.append(this.errorCode);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("isFullPrecision:");
    sb.append(this.isFullPrecision);
    first = false;
    if (!first) sb.append(", ");
    sb.append("isNode:");
    sb.append(this.isNode);
    first = false;
    if (!first) sb.append(", ");
    sb.append("metadataItems:");
    if (this.metadataItems == null) {
      sb.append("null");
    } else {
      sb.append(this.metadataItems);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PageItemStandardSchemeFactory implements SchemeFactory {
    public PageItemStandardScheme getScheme() {
      return new PageItemStandardScheme();
    }
  }

  private static class PageItemStandardScheme extends StandardScheme<PageItem> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PageItem struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.id = iprot.readString();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // URL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.url = iprot.readString();
              struct.setUrlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // LRU
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.lru = iprot.readString();
              struct.setLruIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CRAWLER_TIMESTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.crawlerTimestamp = iprot.readString();
              struct.setCrawlerTimestampIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // HTTP_STATUS_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.httpStatusCode = iprot.readI32();
              struct.setHttpStatusCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // DEPTH
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.depth = iprot.readI32();
              struct.setDepthIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // ERROR_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.errorCode = iprot.readString();
              struct.setErrorCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // IS_FULL_PRECISION
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isFullPrecision = iprot.readBool();
              struct.setIsFullPrecisionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // IS_NODE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isNode = iprot.readBool();
              struct.setIsNodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // METADATA_ITEMS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                struct.metadataItems = new HashMap<String,Set<String>>(2*_map0.size);
                for (int _i1 = 0; _i1 < _map0.size; ++_i1)
                {
                  String _key2; // required
                  Set<String> _val3; // required
                  _key2 = iprot.readString();
                  {
                    org.apache.thrift.protocol.TSet _set4 = iprot.readSetBegin();
                    _val3 = new HashSet<String>(2*_set4.size);
                    for (int _i5 = 0; _i5 < _set4.size; ++_i5)
                    {
                      String _elem6; // required
                      _elem6 = iprot.readString();
                      _val3.add(_elem6);
                    }
                    iprot.readSetEnd();
                  }
                  struct.metadataItems.put(_key2, _val3);
                }
                iprot.readMapEnd();
              }
              struct.setMetadataItemsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PageItem struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.id != null) {
        oprot.writeFieldBegin(ID_FIELD_DESC);
        oprot.writeString(struct.id);
        oprot.writeFieldEnd();
      }
      if (struct.url != null) {
        oprot.writeFieldBegin(URL_FIELD_DESC);
        oprot.writeString(struct.url);
        oprot.writeFieldEnd();
      }
      if (struct.lru != null) {
        oprot.writeFieldBegin(LRU_FIELD_DESC);
        oprot.writeString(struct.lru);
        oprot.writeFieldEnd();
      }
      if (struct.crawlerTimestamp != null) {
        oprot.writeFieldBegin(CRAWLER_TIMESTAMP_FIELD_DESC);
        oprot.writeString(struct.crawlerTimestamp);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(HTTP_STATUS_CODE_FIELD_DESC);
      oprot.writeI32(struct.httpStatusCode);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(DEPTH_FIELD_DESC);
      oprot.writeI32(struct.depth);
      oprot.writeFieldEnd();
      if (struct.errorCode != null) {
        oprot.writeFieldBegin(ERROR_CODE_FIELD_DESC);
        oprot.writeString(struct.errorCode);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(IS_FULL_PRECISION_FIELD_DESC);
      oprot.writeBool(struct.isFullPrecision);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(IS_NODE_FIELD_DESC);
      oprot.writeBool(struct.isNode);
      oprot.writeFieldEnd();
      if (struct.metadataItems != null) {
        oprot.writeFieldBegin(METADATA_ITEMS_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.SET, struct.metadataItems.size()));
          for (Map.Entry<String, Set<String>> _iter7 : struct.metadataItems.entrySet())
          {
            oprot.writeString(_iter7.getKey());
            {
              oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRING, _iter7.getValue().size()));
              for (String _iter8 : _iter7.getValue())
              {
                oprot.writeString(_iter8);
              }
              oprot.writeSetEnd();
            }
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PageItemTupleSchemeFactory implements SchemeFactory {
    public PageItemTupleScheme getScheme() {
      return new PageItemTupleScheme();
    }
  }

  private static class PageItemTupleScheme extends TupleScheme<PageItem> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PageItem struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetUrl()) {
        optionals.set(1);
      }
      if (struct.isSetLru()) {
        optionals.set(2);
      }
      if (struct.isSetCrawlerTimestamp()) {
        optionals.set(3);
      }
      if (struct.isSetHttpStatusCode()) {
        optionals.set(4);
      }
      if (struct.isSetDepth()) {
        optionals.set(5);
      }
      if (struct.isSetErrorCode()) {
        optionals.set(6);
      }
      if (struct.isSetIsFullPrecision()) {
        optionals.set(7);
      }
      if (struct.isSetIsNode()) {
        optionals.set(8);
      }
      if (struct.isSetMetadataItems()) {
        optionals.set(9);
      }
      oprot.writeBitSet(optionals, 10);
      if (struct.isSetId()) {
        oprot.writeString(struct.id);
      }
      if (struct.isSetUrl()) {
        oprot.writeString(struct.url);
      }
      if (struct.isSetLru()) {
        oprot.writeString(struct.lru);
      }
      if (struct.isSetCrawlerTimestamp()) {
        oprot.writeString(struct.crawlerTimestamp);
      }
      if (struct.isSetHttpStatusCode()) {
        oprot.writeI32(struct.httpStatusCode);
      }
      if (struct.isSetDepth()) {
        oprot.writeI32(struct.depth);
      }
      if (struct.isSetErrorCode()) {
        oprot.writeString(struct.errorCode);
      }
      if (struct.isSetIsFullPrecision()) {
        oprot.writeBool(struct.isFullPrecision);
      }
      if (struct.isSetIsNode()) {
        oprot.writeBool(struct.isNode);
      }
      if (struct.isSetMetadataItems()) {
        {
          oprot.writeI32(struct.metadataItems.size());
          for (Map.Entry<String, Set<String>> _iter9 : struct.metadataItems.entrySet())
          {
            oprot.writeString(_iter9.getKey());
            {
              oprot.writeI32(_iter9.getValue().size());
              for (String _iter10 : _iter9.getValue())
              {
                oprot.writeString(_iter10);
              }
            }
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PageItem struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(10);
      if (incoming.get(0)) {
        struct.id = iprot.readString();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.url = iprot.readString();
        struct.setUrlIsSet(true);
      }
      if (incoming.get(2)) {
        struct.lru = iprot.readString();
        struct.setLruIsSet(true);
      }
      if (incoming.get(3)) {
        struct.crawlerTimestamp = iprot.readString();
        struct.setCrawlerTimestampIsSet(true);
      }
      if (incoming.get(4)) {
        struct.httpStatusCode = iprot.readI32();
        struct.setHttpStatusCodeIsSet(true);
      }
      if (incoming.get(5)) {
        struct.depth = iprot.readI32();
        struct.setDepthIsSet(true);
      }
      if (incoming.get(6)) {
        struct.errorCode = iprot.readString();
        struct.setErrorCodeIsSet(true);
      }
      if (incoming.get(7)) {
        struct.isFullPrecision = iprot.readBool();
        struct.setIsFullPrecisionIsSet(true);
      }
      if (incoming.get(8)) {
        struct.isNode = iprot.readBool();
        struct.setIsNodeIsSet(true);
      }
      if (incoming.get(9)) {
        {
          org.apache.thrift.protocol.TMap _map11 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.SET, iprot.readI32());
          struct.metadataItems = new HashMap<String,Set<String>>(2*_map11.size);
          for (int _i12 = 0; _i12 < _map11.size; ++_i12)
          {
            String _key13; // required
            Set<String> _val14; // required
            _key13 = iprot.readString();
            {
              org.apache.thrift.protocol.TSet _set15 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
              _val14 = new HashSet<String>(2*_set15.size);
              for (int _i16 = 0; _i16 < _set15.size; ++_i16)
              {
                String _elem17; // required
                _elem17 = iprot.readString();
                _val14.add(_elem17);
              }
            }
            struct.metadataItems.put(_key13, _val14);
          }
        }
        struct.setMetadataItemsIsSet(true);
      }
    }
  }

}

