/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package fr.sciencespo.medialab.hci.memorystructure.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class PingPong implements org.apache.thrift.TBase<PingPong, PingPong._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PingPong");

  private static final org.apache.thrift.protocol.TField PING_FIELD_DESC = new org.apache.thrift.protocol.TField("ping", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PONG_FIELD_DESC = new org.apache.thrift.protocol.TField("pong", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PingPongStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PingPongTupleSchemeFactory());
  }

  public String ping; // required
  public String pong; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PING((short)1, "ping"),
    PONG((short)2, "pong");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PING
          return PING;
        case 2: // PONG
          return PONG;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PING, new org.apache.thrift.meta_data.FieldMetaData("ping", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PONG, new org.apache.thrift.meta_data.FieldMetaData("pong", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PingPong.class, metaDataMap);
  }

  public PingPong() {
  }

  public PingPong(
    String ping,
    String pong)
  {
    this();
    this.ping = ping;
    this.pong = pong;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PingPong(PingPong other) {
    if (other.isSetPing()) {
      this.ping = other.ping;
    }
    if (other.isSetPong()) {
      this.pong = other.pong;
    }
  }

  public PingPong deepCopy() {
    return new PingPong(this);
  }

  @Override
  public void clear() {
    this.ping = null;
    this.pong = null;
  }

  public String getPing() {
    return this.ping;
  }

  public PingPong setPing(String ping) {
    this.ping = ping;
    return this;
  }

  public void unsetPing() {
    this.ping = null;
  }

  /** Returns true if field ping is set (has been assigned a value) and false otherwise */
  public boolean isSetPing() {
    return this.ping != null;
  }

  public void setPingIsSet(boolean value) {
    if (!value) {
      this.ping = null;
    }
  }

  public String getPong() {
    return this.pong;
  }

  public PingPong setPong(String pong) {
    this.pong = pong;
    return this;
  }

  public void unsetPong() {
    this.pong = null;
  }

  /** Returns true if field pong is set (has been assigned a value) and false otherwise */
  public boolean isSetPong() {
    return this.pong != null;
  }

  public void setPongIsSet(boolean value) {
    if (!value) {
      this.pong = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PING:
      if (value == null) {
        unsetPing();
      } else {
        setPing((String)value);
      }
      break;

    case PONG:
      if (value == null) {
        unsetPong();
      } else {
        setPong((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PING:
      return getPing();

    case PONG:
      return getPong();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PING:
      return isSetPing();
    case PONG:
      return isSetPong();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PingPong)
      return this.equals((PingPong)that);
    return false;
  }

  public boolean equals(PingPong that) {
    if (that == null)
      return false;

    boolean this_present_ping = true && this.isSetPing();
    boolean that_present_ping = true && that.isSetPing();
    if (this_present_ping || that_present_ping) {
      if (!(this_present_ping && that_present_ping))
        return false;
      if (!this.ping.equals(that.ping))
        return false;
    }

    boolean this_present_pong = true && this.isSetPong();
    boolean that_present_pong = true && that.isSetPong();
    if (this_present_pong || that_present_pong) {
      if (!(this_present_pong && that_present_pong))
        return false;
      if (!this.pong.equals(that.pong))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(PingPong other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    PingPong typedOther = (PingPong)other;

    lastComparison = Boolean.valueOf(isSetPing()).compareTo(typedOther.isSetPing());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPing()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ping, typedOther.ping);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPong()).compareTo(typedOther.isSetPong());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPong()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pong, typedOther.pong);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PingPong(");
    boolean first = true;

    sb.append("ping:");
    if (this.ping == null) {
      sb.append("null");
    } else {
      sb.append(this.ping);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("pong:");
    if (this.pong == null) {
      sb.append("null");
    } else {
      sb.append(this.pong);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PingPongStandardSchemeFactory implements SchemeFactory {
    public PingPongStandardScheme getScheme() {
      return new PingPongStandardScheme();
    }
  }

  private static class PingPongStandardScheme extends StandardScheme<PingPong> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PingPong struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PING
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ping = iprot.readString();
              struct.setPingIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PONG
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.pong = iprot.readString();
              struct.setPongIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PingPong struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.ping != null) {
        oprot.writeFieldBegin(PING_FIELD_DESC);
        oprot.writeString(struct.ping);
        oprot.writeFieldEnd();
      }
      if (struct.pong != null) {
        oprot.writeFieldBegin(PONG_FIELD_DESC);
        oprot.writeString(struct.pong);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PingPongTupleSchemeFactory implements SchemeFactory {
    public PingPongTupleScheme getScheme() {
      return new PingPongTupleScheme();
    }
  }

  private static class PingPongTupleScheme extends TupleScheme<PingPong> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PingPong struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPing()) {
        optionals.set(0);
      }
      if (struct.isSetPong()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPing()) {
        oprot.writeString(struct.ping);
      }
      if (struct.isSetPong()) {
        oprot.writeString(struct.pong);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PingPong struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.ping = iprot.readString();
        struct.setPingIsSet(true);
      }
      if (incoming.get(1)) {
        struct.pong = iprot.readString();
        struct.setPongIsSet(true);
      }
    }
  }

}

